### ISSUE TITLE
Workflows

### ISSUE THREAD

**Issue by megastary** [houby-studio/lazy-admin#4]
Moving current project notes to Issue as this feature is becoming quite large to handle in project dashboard.

## How does workflow pass params to next command

Mostly done testing in ./test/workflow-scenarios.ps1
Note: Workflows should obviously accept parameters from JSON output, but could also receive raw string to single param. Or whole output could be available as variable.

## Tasks to do

- [x] Workflows should allow for multiselect in table view
Note: Done via QTable selection option - thus allowing to use 'none', 'single', 'multiple'
- [x] Come up with a way to pass results id to data table to allow selections (OR should Lazy Admin just create hidden Ids for each row?)
- [x] Come up with a way to pass parameters to next parameters dialog. Currently selected results are synced to 'resultsSelected' object.
- [x] Come up with a way to let results window know, if script is workflow and if current workflow step was last or not (set index like -1 or something like that?) so we correctly show workflow next button and possibly allow selections from results
- [x] More changes to scripts definitions may be required

**Comment by megastary** [comment]
Script definitions: 
- remove type - Lazy Admin can recognize workflow just by having key workflow
- renamed passhtru to acceptsParams as that parameter makes previous commands results table change behavior (hopefully makes more sense)

History:
Should history keep each step in workflow separate remembering all params and inputs no matter if received from previous command or from user input?
Or should workflow be saved as array, allowing user to backtrack every single step if he wanted to.
How do we allow user to hop to step 3 from history and finish all remaining steps.

Next workflow step prototype - shallow copy problem, would need to use lodash
```javascript
nextWorkflowStep () {
      this.displayResultsDiag = false
      this.displayCommandDiag = true // TODO: Currently not required, but we may close commands dialog after showing results diag
      // By forcing currentCommand to be array, we can detect workflow and apply pagination and other options for multiple selection
      this.currentCommand = []
      // For each selected result, push command object to currentCommand array
      for (let i = 0; i < this.resultsSelected.length; i++) {
        let tempCommand = Object.assign({}, this.currentCommandMaster.workflow[this.currentWorkflowIndex])
        // For each passed parameter expected in workflow, add to currendCommand instance
        for (let j = 0; j < tempCommand.passedParameters.length; j++) {
          tempCommand.parameters.push(this.resultsSelected[tempCommand.passedParameters[j].propertyName])
        }
        console.log('tempCommand', tempCommand)
        console.log('tempCommand.parameters', tempCommand.parameters)
        console.log('this.resultsSelected', this.resultsSelected)
      }
      // this.currentCommand.push(this.currentCommandMaster.workflow[this.currentWorkflowIndex])
      // TODO: What if there is no passed parameter or it is not array (has no length)
    }
```

**Comment by megastary** [comment]
TODO: At execute command, do not try to create multidimensional array, instead do:
check how many selected items are (if none, set '1')
for i < selected items
run obtaining input just like now, except associative call will be i + "__" + param.parameter

If param window will have checkbox to use same input for all, either copy to all cards, or make check at executeCommand and add params only from "1" inputs for all numbers (need to think how to disallow user from entering values to other cells)

**Comment by megastary** [comment]
Need to create wiki for parameter:
{{__raw_argument}}

which can be used in workflow commands and gets replaced by raw results from previous command (results.output)

**Comment by megastary** [comment]
Version 0.3.0 now supports both scenarios! Next days will show how buggy it is.

**Comment by megastary** [comment]
should currentCommand also hold value whether it is safe to rerun or not? Most commands probably can be rerun with same parameters, but those who rely on either $? or __raw_argument or other parameter overwritten each time command is run, getting same results for second and subsequent times is impossible.
Cannot add @hide to results dialog, as it would break workflows. Probably need to add event listener on either close button or ESC button, to check for that value and potentially kill the command dialog.

**Comment by megastary** [comment]
All features added, workflows done. Wiki page for {{__raw_argument}} moved to WIKI project
